# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-15 19:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travel_app', '0002_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='joined_by',
            field=models.ManyToManyField(related_name='joins', to='travel_app.User'),
        ),
        migrations.AddField(
            model_name='plan',
            name='planned_by',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='travel_app.User'),
            preserve_default=False,
        ),
    ]
