# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-16 18:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_app', '0003_auto_20171215_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='travel_date_from',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='plan',
            name='travel_date_to',
            field=models.DateField(),
        ),
    ]
